"""
Concrete infrastructure implementations:
- CrossEncoderReranker
- FileSystemDatasetReader
- NetworkXExporter
"""

import json
import os
from pathlib import Path
from typing import List

import networkx as nx

from src.core.contracts import (
    ICrossEncoderReranker,
    IDatasetReader,
    IGraphExporter,
    SearchResult,
)
from src.core.entities import Dataset


class CrossEncoderReranker(ICrossEncoderReranker):
    """Cross-encoder reranker using sentence-transformers cross-encoder models."""

    def __init__(self, model_name: str = "cross-encoder/ms-marco-MiniLM-L-6-v2"):
        self._model_name = model_name
        self._model = None

    def _get_model(self):
        if self._model is None:
            try:
                from sentence_transformers import CrossEncoder
                self._model = CrossEncoder(self._model_name)
            except ImportError:
                self._model = None
        return self._model

    def rerank(self, query: str, candidates: List[SearchResult]) -> List[SearchResult]:
        model = self._get_model()
        if not model:
            return candidates
        pairs = [(query, r.content) for r in candidates]
        scores = model.predict(pairs)
        for r, score in zip(candidates, scores):
            r.score = float(score)
        candidates.sort(key=lambda r: r.score, reverse=True)
        return candidates


class FileSystemDatasetReader(IDatasetReader):
    """
    Loads a Dataset from JSON files generated by the generator module.
    Expected layout:
        base_path/
          tenant_id/
            tickets/      <artifact_id>.json
            commits/      <artifact_id>.json
            ...
    """

    _ENTITY_TYPES = [
        "tickets", "commits", "incidents", "slack_messages",
        "pull_requests", "requirements", "deployments", "services",
        "teams", "employees", "apis", "adrs", "runbooks", "repositories",
        "releases", "metrics", "logs", "alerts", "postmortems", "test_cases",
    ]

    def load(self, base_path: str) -> Dataset:
        root = Path(base_path)
        if not root.exists():
            raise FileNotFoundError(f"Data directory not found: {base_path}")

        raw: dict = {k: {} for k in self._ENTITY_TYPES}

        for tenant_dir in root.iterdir():
            if not tenant_dir.is_dir():
                continue
            tenant_id = tenant_dir.name

            for entity_type in self._ENTITY_TYPES:
                entity_dir = tenant_dir / entity_type
                if entity_type == "slack_messages" and not entity_dir.exists():
                    entity_dir = tenant_dir / "slack"
                if not entity_dir.exists():
                    continue
                for json_file in entity_dir.glob("*.json"):
                    with open(json_file, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    artifact_id = f"{tenant_id}::{json_file.stem}"
                    # Inject tenant_id + composite id
                    data.setdefault("id", artifact_id)
                    data.setdefault("tenant_id", tenant_id)
                    raw[entity_type][artifact_id] = data

        # Build typed entity dicts using Pydantic models
        from src.core.entities import (
            Ticket, Commit, Incident, SlackMessage, PullRequest,
            Requirement, Deployment, Service, Team, Employee, API,
            ArchitectureDecisionRecord, Runbook, Repository, Release,
            Metric, Log, Alert, Postmortem, TestCase,
        )

        type_map = {
            "tickets": Ticket,
            "commits": Commit,
            "incidents": Incident,
            "slack_messages": SlackMessage,
            "pull_requests": PullRequest,
            "requirements": Requirement,
            "deployments": Deployment,
            "services": Service,
            "teams": Team,
            "employees": Employee,
            "apis": API,
            "adrs": ArchitectureDecisionRecord,
            "runbooks": Runbook,
            "repositories": Repository,
            "releases": Release,
            "metrics": Metric,
            "logs": Log,
            "alerts": Alert,
            "postmortems": Postmortem,
            "test_cases": TestCase,
        }

        parsed: dict = {}
        for entity_type, model_cls in type_map.items():
            parsed[entity_type] = {}
            for artifact_id, data in raw[entity_type].items():
                try:
                    if entity_type == "tickets":
                        fields = data.get("fields", {})
                        data = {
                            "id": data.get("id"),
                            "tenant_id": data.get("tenant_id"),
                            "key": data.get("key"),
                            "summary": fields.get("summary", ""),
                            "description": fields.get("description", ""),
                            "issuetype": fields.get("issuetype", {}).get("name", ""),
                            "status": fields.get("status", {}).get("name", ""),
                            "assignee_id": fields.get("assignee"),
                            "created_at": fields.get("created"),
                            "updated_at": fields.get("updated"),
                            "requirement_id": fields.get("customfield_requirement_id"),
                            "service_ids": fields.get("customfield_service_ids", [])
                        }
                    elif entity_type == "commits":
                        commit = data.get("commit", {})
                        author = commit.get("author", {})
                        data = {
                            "id": data.get("id"),
                            "tenant_id": data.get("tenant_id"),
                            "sha": data.get("sha"),
                            "message": commit.get("message", ""),
                            "author_name": author.get("name", ""),
                            "date": author.get("date"),
                            "repository": data.get("repository", ""),
                            "files_changed": commit.get("files_changed", []),
                            "diff_summary": commit.get("diff_summary")
                        }
                    elif entity_type == "slack_messages":
                        from datetime import datetime
                        ts = data.get("ts")
                        dt = datetime.fromtimestamp(float(ts)) if ts else datetime.now()
                        data = {
                            "id": data.get("id"),
                            "tenant_id": data.get("tenant_id"),
                            "channel": data.get("channel", ""),
                            "text": data.get("text", ""),
                            "user_id": data.get("user") or data.get("user_id", ""),
                            "timestamp": dt
                        }

                    parsed[entity_type][artifact_id] = model_cls(**data)
                except Exception:
                    pass  # Skip malformed records

        return Dataset(**parsed)


class NetworkXExporter(IGraphExporter):
    """Exports a NetworkX graph to GraphML format."""

    def export(self, graph: nx.DiGraph, output_dir: str, filename: str) -> None:
        g = graph.copy()

        # Sanitize graph attributes for GraphML compatibility
        for n, data in g.nodes(data=True):
            if "obj" in data:
                try:
                    data["obj_json"] = json.dumps(data["obj"].model_dump(), default=str)
                except Exception:
                    data["obj_json"] = str(data["obj"])
                del data["obj"]

        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        out_file = out_path / filename
        nx.write_graphml(g, str(out_file))
